# Generated by Django 5.1.3 on 2026-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, help_text='Student SR code/number', max_length=20, null=True, unique=True),
        ),
    ]
