# Generated by Django 4.2.8 on 2025-12-30 01:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique class code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Class name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed class description')),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.CharField(help_text='Class schedule (e.g., Mon/Wed 10:00 AM)', max_length=200)),
                ('platform_url', models.URLField(blank=True, help_text='Link to class platform or meeting', validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Whether class is currently active')),
                ('start_date', models.DateField(help_text='Class start date')),
                ('end_date', models.DateField(help_text='Class end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(help_text='Instructor for this class', on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='Enrollment date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether enrollment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(help_text='Enrolled class', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class')),
                ('student', models.ForeignKey(help_text='Student user', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student', 'class_ref'], name='classes_stu_student_94abf2_idx'), models.Index(fields=['class_ref', 'is_active'], name='classes_stu_class_r_7dbd88_idx')],
                'unique_together': {('student', 'class_ref')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(help_text='Sequential session number')),
                ('date', models.DateField(help_text='Date of the session')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(help_text='Session end time')),
                ('topic', models.CharField(help_text='Session topic or lecture title', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Additional session notes')),
                ('is_held', models.BooleanField(default=True, help_text='Whether session was actually held')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(help_text='Associated class', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.class')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['class_ref', 'date'], name='classes_ses_class_r_b0fb41_idx'), models.Index(fields=['date'], name='classes_ses_date_080bef_idx')],
                'unique_together': {('class_ref', 'date', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['code'], name='classes_cla_code_4ddb04_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['instructor'], name='classes_cla_instruc_714de6_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_active'], name='classes_cla_is_acti_cc0d41_idx'),
        ),
    ]
