# Generated by Django 5.1.3 on 2026-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_section_sectioncourse_enrollment_studentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
