# Generated by Django 5.1.3 on 2026-01-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_section_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncourse',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Assigned instructor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_section_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SectionCourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Application note or message')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_course_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_section_applications', to=settings.AUTH_USER_MODEL)),
                ('section_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='classes.sectioncourse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='classes_sec_instruc_20d75d_idx'), models.Index(fields=['section_course', 'status'], name='classes_sec_section_ec7ac5_idx')],
                'unique_together': {('section_course', 'instructor')},
            },
        ),
    ]
