# Generated by Django 5.1.3 on 2026-01-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_courseapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='year_level',
            field=models.ForeignKey(blank=True, help_text='Optional: leave blank to apply to all year levels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='classes.yearlevel'),
        ),
    ]
