# Generated by Django 4.2.8 on 2025-12-30 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('left_early', 'Left Early')], default='absent', help_text='Attendance status', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Time of check-in', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Time of check-out', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of marking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(help_text='Instructor who marked attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Session attended', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.session')),
                ('student', models.ForeignKey(help_text='Student who attended', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-session__date', 'student__last_name'],
                'indexes': [models.Index(fields=['student', 'session'], name='attendance__student_992f1c_idx'), models.Index(fields=['session', 'status'], name='attendance__session_8dae34_idx'), models.Index(fields=['student', 'marked_at'], name='attendance__student_d2a188_idx'), models.Index(fields=['status'], name='attendance__status_741eb8_idx')],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
